#!/usr/bin/env python3
# ============================================================
# ARCHON PRIME MODULE HEADER
# module_id:            M-MOD-SYNTH
# module_name:          module_synthesizer
# analysis_domain:      semantic_analysis
# module_role:          synthesis
# execution_entry:      run
# mutation_capability:  false
# safety_classification: READ_ONLY
# spec_reference:       [SPEC-AP-V2.1]
# ============================================================

"""
ARCHON PRIME — Module Synthesizer
====================================
Generates prototype Python module files from reconstruction plans.

Synthesis rules:
  - Each plan entry produces one .py file under <output_root>/synthesized_modules/
  - Generated files contain:
      * Docstring explaining origin, cluster source, and domain target
      * List comment of fragment IDs used
      * Structured stubs for each fragment (function signature + docstring + TODO body)
      * Dependency import block at the top
  - No runtime integration is emitted automatically (only scaffold + TODO markers)

Inputs:
    fragment_module_reconstruction_plan.json
    logic_fragments.json                      (for function signature details)

Outputs (written to <output_root>/synthesized_modules/):
    One .py file per plan entry
    synthesized_module_manifest.json          (index of all generated files)
"""

import ast
import json
import os
import re
import textwrap
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_OUTPUT_ROOT = "_Dev_Resources/Reports/ARCHON_DIAGNOSTICS"

OUTPUT_ROOT = Path(
    os.environ.get("ARCHON_OUTPUT_ROOT", DEFAULT_OUTPUT_ROOT)
)
OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

RUN_TS = datetime.now(timezone.utc).isoformat()

# ---------------------------------------------------------------------------
# Code generation utilities
# ---------------------------------------------------------------------------

_SPLIT_RE = re.compile(r"[_\.\-\s]+")

# Python identifiers that cannot be used as argument names
_PY_BUILTINS = frozenset(dir(__builtins__)) | {
    "False", "None", "True", "and", "as", "assert", "async", "await",
    "break", "class", "continue", "def", "del", "elif", "else", "except",
    "finally", "for", "from", "global", "if", "import", "in", "is",
    "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try",
    "while", "with", "yield",
}


def _safe_identifier(name: str) -> str:
    """Strip unsafe characters to produce a valid Python identifier."""
    cleaned = re.sub(r"[^a-zA-Z0-9_]", "_", str(name))
    if cleaned and cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned or "_arg"


def _arg_list(args: list) -> str:
    """Build a function arg list string from raw args, keeping *args / **kwargs safe."""
    seen: set[str] = set()
    result = []
    for raw in args:
        s = str(raw).strip()
        # Remove type annotations if present
        name_part = s.split(":")[0].strip()
        # Strip leading * / **
        prefix = ""
        if name_part.startswith("**"):
            prefix, name_part = "**", name_part[2:]
        elif name_part.startswith("*"):
            prefix, name_part = "*", name_part[1:]
        safe = _safe_identifier(name_part)
        # De-duplicate
        if safe in seen:
            safe = f"{safe}_{len(seen)}"
        seen.add(safe)
        result.append(f"{prefix}{safe}")
    return ", ".join(result)


def _render_stub(frag: dict, indent: str = "") -> str:
    """Render a single function stub from a fragment record."""
    fn_name = _safe_identifier(frag.get("function", "fragment"))
    args = frag.get("args", [])
    arg_str = _arg_list(args)
    docstring = (frag.get("docstring", "") or "").strip()
    is_async = frag.get("is_async", False)
    body_lines = frag.get("body_lines", 0)
    lineno = frag.get("lineno", 0)
    source_file = frag.get("file", "unknown")

    prefix = "async " if is_async else ""
    doc_body = (
        f'    """{textwrap.shorten(docstring, width=120, placeholder="...")}\n\n'
        f'    Origin: {source_file}:{lineno}  (body ~{body_lines} lines)\n    """\n'
        if docstring
        else f'    """Origin: {source_file}:{lineno}  (body ~{body_lines} lines)"""\n'
    )
    stub = (
        f"{indent}{prefix}def {fn_name}({arg_str}):\n"
        f"{indent}{doc_body}"
        f"{indent}    # TODO: reconstruct logic from source fragment\n"
        f"{indent}    raise NotImplementedError(\n"
        f'{indent}        "Stub generated by ARCHON PRIME module_synthesizer — '
        f'reconstruct from {source_file}:{lineno}"\n'
        f"{indent}    )\n"
    )
    return stub


def _render_module(plan: dict, frag_lookup: dict) -> str:
    """Render a complete prototype Python module source string."""
    module_name = plan["module_name"]
    cluster_source = plan["cluster_source"]
    domain = plan["target_runtime_domain"]
    confidence = plan.get("confidence_score", 0.0)
    deps = plan.get("dependency_requirements", [])
    notes = plan.get("integration_notes", "")
    members = plan.get("fragment_members", [])
    n_frags = plan.get("fragment_count", len(members))

    # Header
    lines = [
        "#!/usr/bin/env python3",
        f"# Generated by ARCHON PRIME module_synthesizer — {RUN_TS}",
        f"# Cluster source : {cluster_source}",
        f"# Target domain  : {domain}  (confidence {confidence:.2f})",
        f"# Fragment count : {n_frags}",
        "",
        '"""',
        f"{module_name}",
        "=" * len(module_name),
        "ARCHON PRIME — Prototype reconstructed module.",
        "",
        f"Cluster source    : {cluster_source}",
        f"Target domain     : {domain}",
        f"Confidence score  : {confidence:.2f}",
        f"Fragments used    : {n_frags}",
        "",
        "Integration notes:",
        textwrap.fill(notes, width=78, initial_indent="  ", subsequent_indent="  "),
        "",
        "Fragment IDs:",
    ]
    for mid in members[:50]:
        lines.append(f"  - {mid}")
    if len(members) > 50:
        lines.append(f"  ... and {len(members) - 50} more")
    lines += [
        "",
        "IMPORTANT: This is a scaffold only.",
        "No runtime integration is performed automatically.",
        "All function bodies contain NotImplementedError stubs.",
        "Review each stub and reconstruct logic from the identified source.",
        '"""',
        "",
    ]

    # Imports
    stdlib_always = ["from __future__ import annotations", "from typing import Any"]
    lines.extend(stdlib_always)
    if deps:
        lines.append("# Inferred dependency hints (verify before use):")
        for dep in deps:
            lines.append(f"# import {dep}")
    lines += ["", ""]

    # Function stubs
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# Reconstructed function stubs")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("")

    rendered: set[str] = set()
    for fid in members:
        frag = frag_lookup.get(fid)
        if not frag:
            continue
        fn_name = _safe_identifier(frag.get("function", "fragment"))
        if fn_name in rendered:
            continue
        rendered.add(fn_name)
        lines.append(_render_stub(frag))

    if not rendered:
        lines += [
            "def placeholder() -> None:",
            '    """No fragments resolved for this cluster."""',
            "    raise NotImplementedError",
            "",
        ]

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def run(output_root: Path = OUTPUT_ROOT) -> list[str]:
    """
    Load reconstruction plan and fragment data; synthesize prototype modules.
    Returns list of written file paths.
    """
    output_root.mkdir(parents=True, exist_ok=True)
    synth_dir = output_root / "synthesized_modules"
    synth_dir.mkdir(parents=True, exist_ok=True)

    print("ARCHON PRIME — Module Synthesizer")
    print(f"  Output : {synth_dir}")

    # Load plan
    plan_path = output_root / "fragment_module_reconstruction_plan.json"
    if not plan_path.exists():
        raise FileNotFoundError(
            "fragment_module_reconstruction_plan.json not found — run module_reconstruction_planner first."
        )
    plan_data = json.loads(plan_path.read_text(encoding="utf-8"))
    plans = plan_data.get("plans", plan_data) if isinstance(plan_data, dict) else plan_data

    # Load fragments
    frag_path = output_root / "logic_fragments.json"
    frag_list = json.loads(frag_path.read_text(encoding="utf-8")) if frag_path.exists() else []
    frag_lookup: dict[str, dict] = {f["fragment_id"]: f for f in frag_list}

    written: list[str] = []
    manifest: list[dict] = []

    for plan in plans:
        module_name = plan["module_name"]
        out_file = synth_dir / f"{module_name}.py"

        source = _render_module(plan, frag_lookup)
        out_file.write_text(source, encoding="utf-8")

        written.append(str(out_file))
        manifest.append({
            "module_name": module_name,
            "file": str(out_file.relative_to(output_root)),
            "cluster_source": plan["cluster_source"],
            "target_runtime_domain": plan["target_runtime_domain"],
            "fragment_count": plan["fragment_count"],
            "confidence_score": plan.get("confidence_score", 0.0),
        })

    # Write manifest
    manifest_path = output_root / "synthesized_module_manifest.json"
    manifest_path.write_text(
        json.dumps(
            {
                "generated_at": RUN_TS,
                "total_modules": len(manifest),
                "synthesized_dir": str(synth_dir),
                "modules": manifest,
            },
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )

    print(f"  [WRITE] {len(written)} modules → {synth_dir}")
    print(f"  [WRITE] manifest → {manifest_path}")

    return written


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="ARCHON Module Synthesizer")
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT_ROOT,
        help="Output root — synthesized_modules/ subdir will be created here.",
    )
    args = parser.parse_args()
    run(output_root=args.output)


if __name__ == "__main__":
    main()
