# HEADER_TYPE: PRODUCTION_RUNTIME_MODULE
# AUTHORITY: LOGOS_SYSTEM
# GOVERNANCE: ENABLED
# EXECUTION: CONTROLLED
# MUTABILITY: IMMUTABLE_LOGIC
# VERSION: 1.0.0

"""
LOGOS_MODULE_METADATA
---------------------
module_name: persist_identity
runtime_layer: inferred
role: inferred
agent_binding: None
protocol_binding: None
boot_phase: inferred
expected_imports: []
provides: []
depends_on_runtime_state: False
failure_mode:
  type: unknown
  notes: ""
rewrite_provenance:
  source: System_Stack/Logos_Protocol/Activation_Sequencer/Identity_Generator/Agent_ID_Spin_Up/persist_identity.py
  rewrite_phase: Phase_B
  rewrite_timestamp: 2026-01-18T23:03:31.726474
observability:
  log_channel: None
  metrics: disabled
---------------------
"""

"""
Persist the formal identity generated by the recursion engine to canonical locations
so the consciousness subsystems and the logos core can read it.

Writes a small JSON file to each target path.
"""
import json
from pathlib import Path
import sys


def persist_identity(root: Path | None = None) -> None:
    """Persist the resolved identity JSON to expected targets."""

    root = Path(root) if root else Path.cwd()
    discharge = root / "Logos_Agent" / "state" / "lem_discharge_state.json"
    if not discharge.exists():
        print("No discharge state found at", discharge)
        sys.exit(1)

    with open(discharge, "r", encoding="utf-8") as fh:
        data = json.load(fh)

    formal_identity = data.get("formal_identity") or data.get("generated_identity")
    if not formal_identity:
        import hashlib

        raw = (
            f"{data.get('agent_id','')}-"
            f"{data.get('resolved_at','')}-"
            f"{data.get('proof_file','')}"
        )
        formal_identity = (
            "LOGOS_AGENT_IDENTITY::"
            + data.get("agent_id", "UNKNOWN")
            + "::"
            + hashlib.sha256(raw.encode()).hexdigest()
        )

    payload = {
        "formal_identity": formal_identity,
        "agent_id": data.get("agent_id"),
        "resolved_at": data.get("resolved_at"),
        "proof_file": data.get("proof_file"),
    }

    targets = [
        root / "Synthetic_Cognition_Protocol" / "consciousness" / "agent_identity.json",
        root / "Advanced_Reasoning_Protocol" / "logos_core copy" / "agent_identity.json",
        root / "Logos_Agent" / "state" / "agent_identity.json",
    ]

    for t in targets:
        try:
            t.parent.mkdir(parents=True, exist_ok=True)
            with open(t, "w", encoding="utf-8") as fh:
                json.dump(payload, fh, indent=2)
            print("Wrote identity to", t)
        except Exception as exc:
            print("Failed to write to", t, exc)

    print("Completed. Formal identity:")
    print(formal_identity)


if __name__ == "__main__":
    persist_identity()
