# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CANONICAL IMPORT FACADE — logos.imports.governance
# ║  Generated by ARCHON PRIME / Facade Synthesis Pass
# ║  DO NOT EDIT MANUALLY — re-generate via archon_facade_synthesis.py
# ╚══════════════════════════════════════════════════════════════════════════╝
"""
Canonical facade namespace: logos.imports.governance

This module re-exports symbols from the runtime subsystem so that consumers
can import them through a stable, shallow namespace instead of deep internal
module paths.

Usage:
    from logos.imports.governance import <Symbol>

    instead of:
    from LOGOS_SYSTEM.<...deep path...> import <Symbol>
"""

from __future__ import annotations

# ── lazy symbol re-exports ────────────────────────────────────────────────────
# Each block below tries to import from the underlying implementation module.
# If that module is unavailable (e.g. optional dependency, dev environment),
# the symbol is set to None and the import failure is silently absorbed so
# the facade itself remains importable at all times.

try:
    from LOGOS_SYSTEM.RUNTIME_CORES.LOGOS_SYSTEM.autonomous_learning import ReasoningGap
except Exception:  # noqa: BLE001
    ReasoningGap = None  # type: ignore[assignment]

try:
    from LOGOS_SYSTEM.Runtime_Spine.Lock_And_Key.lock_and_key import LockAndKeyFailure, execute_lock_and_key
except Exception:  # noqa: BLE001
    LockAndKeyFailure = None  # type: ignore[assignment]
    execute_lock_and_key = None  # type: ignore[assignment]

try:
    from LOGOS_SYSTEM.SYSTEM.RUNTIME_EXECUTION_CORE.Logos_Agents.agent_classes import CreatureAgent, TrinitarianAgent
except Exception:  # noqa: BLE001
    CreatureAgent = None  # type: ignore[assignment]
    TrinitarianAgent = None  # type: ignore[assignment]

try:
    from LOGOS_SYSTEM.SYSTEM.RUNTIME_EXECUTION_CORE.Synthetic_Cognition_Protocol.SCP_Core.fractal_orbit_toolkit import FractalOrbitAnalysisToolkit, FractalPattern, FractalScale, OrbitalPrediction, PredictionConfidence, TrinityVector
except Exception:  # noqa: BLE001
    FractalOrbitAnalysisToolkit = None  # type: ignore[assignment]
    FractalPattern = None  # type: ignore[assignment]
    FractalScale = None  # type: ignore[assignment]
    OrbitalPrediction = None  # type: ignore[assignment]
    PredictionConfidence = None  # type: ignore[assignment]
    TrinityVector = None  # type: ignore[assignment]

try:
    from LOGOS_SYSTEM.SYSTEM.RUNTIME_EXECUTION_CORE.Synthetic_Cognition_Protocol.SCP_Tools.Integrations.fractal_mapping import FractalNavigator
except Exception:  # noqa: BLE001
    FractalNavigator = None  # type: ignore[assignment]

try:
    from LOGOS_SYSTEM.SYSTEM_OPERATIONS_PROTOCOL.Audit_Spine.Audit_Logger import AuditLogger
except Exception:  # noqa: BLE001
    AuditLogger = None  # type: ignore[assignment]

try:
    from LOGOS_SYSTEM.SYSTEM_OPERATIONS_PROTOCOL.DRAC_Integration.Core_Binding_Validator import CoreBindingValidator
except Exception:  # noqa: BLE001
    CoreBindingValidator = None  # type: ignore[assignment]

try:
    from LOGOS_SYSTEM.SYSTEM_OPERATIONS_PROTOCOL.DRAC_Integration.DRAC_Handshake import DRACHandshake
except Exception:  # noqa: BLE001
    DRACHandshake = None  # type: ignore[assignment]

try:
    from LOGOS_SYSTEM.SYSTEM_OPERATIONS_PROTOCOL.DRAC_Integration.DRAC_Orchestration_Bridge import DRACOrchestrationBridge
except Exception:  # noqa: BLE001
    DRACOrchestrationBridge = None  # type: ignore[assignment]

try:
    from LOGOS_SYSTEM.SYSTEM_OPERATIONS_PROTOCOL.DRAC_Integration.Overlay_Validator import OverlayValidator
except Exception:  # noqa: BLE001
    OverlayValidator = None  # type: ignore[assignment]

try:
    from LOGOS_SYSTEM.SYSTEM_OPERATIONS_PROTOCOL.Governance_Control.Invariant_Enforcer import InvariantEnforcer
except Exception:  # noqa: BLE001
    InvariantEnforcer = None  # type: ignore[assignment]

try:
    from LOGOS_SYSTEM.SYSTEM_OPERATIONS_PROTOCOL.Policy_Matrix.Compile_Quota_Guard import CompileQuotaGuard
except Exception:  # noqa: BLE001
    CompileQuotaGuard = None  # type: ignore[assignment]

try:
    from LOGOS_SYSTEM.SYSTEM_OPERATIONS_PROTOCOL.Policy_Matrix.SOP_Policy_Matrix import SOPPolicyMatrix
except Exception:  # noqa: BLE001
    SOPPolicyMatrix = None  # type: ignore[assignment]

try:
    from LOGOS_SYSTEM.System_Entry_Point.Agent_Orchestration.agent_orchestration import OrchestrationHalt, prepare_agent_orchestration
except Exception:  # noqa: BLE001
    OrchestrationHalt = None  # type: ignore[assignment]
    prepare_agent_orchestration = None  # type: ignore[assignment]

__all__ = ["AuditLogger", "CompileQuotaGuard", "CoreBindingValidator", "CreatureAgent", "DRACHandshake", "DRACOrchestrationBridge", "FractalNavigator", "FractalOrbitAnalysisToolkit", "FractalPattern", "FractalScale", "InvariantEnforcer", "LockAndKeyFailure", "OrbitalPrediction", "OrchestrationHalt", "OverlayValidator", "PredictionConfidence", "ReasoningGap", "SOPPolicyMatrix", "TrinitarianAgent", "TrinityVector", "execute_lock_and_key", "prepare_agent_orchestration"]

# ── Additions from Boundary Repair Pass ──────────────────────────────────────
try:
    from LOGOS_SYSTEM.GOVERNANCE_ENFORCEMENT.Compatibility_Shims.exceptions import GovernanceDenied
except Exception:  # noqa: BLE001
    GovernanceDenied = None  # type: ignore[assignment]

try:
    from LOGOS_SYSTEM._Governance.Nexus_Validation.Nexus_AST_Validator import NexusASTValidator
except Exception:  # noqa: BLE001
    NexusASTValidator = None  # type: ignore[assignment]

