# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  CANONICAL IMPORT FACADE — logos.imports.mtp
# ║  Generated by ARCHON PRIME / Boundary Violation Repair Pass
# ║  DO NOT EDIT MANUALLY — re-generate via archon_facade_synthesis.py
# ╚══════════════════════════════════════════════════════════════════════════════╝
"""
Canonical facade namespace: logos.imports.mtp

This module re-exports symbols from underlying subsystems so that consumers
can import them through a stable, shallow namespace instead of deep internal
module paths.

Usage:
    from logos.imports.mtp import <Symbol>

    instead of:
    from <deep.internal.path> import <Symbol>
"""

from __future__ import annotations

# ── lazy symbol re-exports ────────────────────────────────────────────────────
# Each block below tries to import from the underlying implementation module.
# If that module is unavailable (e.g. optional dependency, dev environment),
# the symbol is set to None and the import failure is silently absorbed so
# the facade itself remains importable at all times.

try:
    from I2_Integration.I2_Egress_Critique import CritiqueResult, I2EgressCritique
except Exception:  # noqa: BLE001
    CritiqueResult = None  # type: ignore[assignment]
    I2EgressCritique = None  # type: ignore[assignment]

try:
    from MTP_Core.MTP_Fractal_Evaluator import FractalEvaluator, ResonanceScore, StabilityReport
except Exception:  # noqa: BLE001
    FractalEvaluator = None  # type: ignore[assignment]
    ResonanceScore = None  # type: ignore[assignment]
    StabilityReport = None  # type: ignore[assignment]

try:
    from MTP_Core.MTP_Output_Renderer import OutputRenderer, RenderConfig, RenderedOutput, ToneLevel, VerbosityLevel
except Exception:  # noqa: BLE001
    OutputRenderer = None  # type: ignore[assignment]
    RenderConfig = None  # type: ignore[assignment]
    RenderedOutput = None  # type: ignore[assignment]
    ToneLevel = None  # type: ignore[assignment]
    VerbosityLevel = None  # type: ignore[assignment]

try:
    from MTP_Core.MTP_Projection_Engine import ContentEdge, ContentNode, ProjectionEngine, ProjectionResult, SemanticContentGraph
except Exception:  # noqa: BLE001
    ContentEdge = None  # type: ignore[assignment]
    ContentNode = None  # type: ignore[assignment]
    ProjectionEngine = None  # type: ignore[assignment]
    ProjectionResult = None  # type: ignore[assignment]
    SemanticContentGraph = None  # type: ignore[assignment]

try:
    from MTP_Core.MTP_Semantic_Linearizer import DiscourseMode, LinearUnit, LinearizationPlan, SemanticLinearizer
except Exception:  # noqa: BLE001
    DiscourseMode = None  # type: ignore[assignment]
    LinearUnit = None  # type: ignore[assignment]
    LinearizationPlan = None  # type: ignore[assignment]
    SemanticLinearizer = None  # type: ignore[assignment]

try:
    from MTP_Core.MTP_Validation_Gate import ValidationGate, ValidationResult
except Exception:  # noqa: BLE001
    ValidationGate = None  # type: ignore[assignment]
    ValidationResult = None  # type: ignore[assignment]

try:
    from MTP_Nexus.MTP_Nexus import EgressPipelineResult, MTPNexus, PipelineStageRecord
except Exception:  # noqa: BLE001
    EgressPipelineResult = None  # type: ignore[assignment]
    MTPNexus = None  # type: ignore[assignment]
    PipelineStageRecord = None  # type: ignore[assignment]

try:
    from Nexus import NexusParticipant, StandardNexus, StatePacket
except Exception:  # noqa: BLE001
    NexusParticipant = None  # type: ignore[assignment]
    StandardNexus = None  # type: ignore[assignment]
    StatePacket = None  # type: ignore[assignment]

