# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  CANONICAL IMPORT FACADE — logos.imports.safety_shims
# ║  Generated by ARCHON PRIME / Boundary Violation Repair Pass
# ║  DO NOT EDIT MANUALLY — re-generate via archon_facade_synthesis.py
# ╚══════════════════════════════════════════════════════════════════════════════╝
"""
Canonical facade namespace: logos.imports.safety_shims

This module re-exports symbols from underlying subsystems so that consumers
can import them through a stable, shallow namespace instead of deep internal
module paths.

Usage:
    from logos.imports.safety_shims import <Symbol>

    instead of:
    from <deep.internal.path> import <Symbol>
"""

from __future__ import annotations

# ── lazy symbol re-exports ────────────────────────────────────────────────────
# Each block below tries to import from the underlying implementation module.
# If that module is unavailable (e.g. optional dependency, dev environment),
# the symbol is set to None and the import failure is silently absorbed so
# the facade itself remains importable at all times.

try:
    from LOGOS_SYSTEM.Agent_Safety_Shims.Capability_Router import CapabilityRouter, router_allows_memory_write, validate_authz_memory_bounded
except Exception:  # noqa: BLE001
    CapabilityRouter = None  # type: ignore[assignment]
    router_allows_memory_write = None  # type: ignore[assignment]
    validate_authz_memory_bounded = None  # type: ignore[assignment]

try:
    from LOGOS_SYSTEM.Agent_Safety_Shims.Phase_E_Capability_Router import CapabilityRouter, router_allows_memory_write, validate_authz_memory_bounded
except Exception:  # noqa: BLE001
    CapabilityRouter = None  # type: ignore[assignment]
    router_allows_memory_write = None  # type: ignore[assignment]
    validate_authz_memory_bounded = None  # type: ignore[assignment]

