# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CANONICAL IMPORT FACADE — logos.imports.startup
# ║  Generated by ARCHON PRIME / Facade Synthesis Pass
# ║  DO NOT EDIT MANUALLY — re-generate via archon_facade_synthesis.py
# ╚══════════════════════════════════════════════════════════════════════════╝
"""
Canonical facade namespace: logos.imports.startup

This module re-exports symbols from the runtime subsystem so that consumers
can import them through a stable, shallow namespace instead of deep internal
module paths.

Usage:
    from logos.imports.startup import <Symbol>

    instead of:
    from LOGOS_SYSTEM.<...deep path...> import <Symbol>
"""

from __future__ import annotations

# ── lazy symbol re-exports ────────────────────────────────────────────────────
# Each block below tries to import from the underlying implementation module.
# If that module is unavailable (e.g. optional dependency, dev environment),
# the symbol is set to None and the import failure is silently absorbed so
# the facade itself remains importable at all times.

try:
    from LOGOS_SYSTEM.RUNTIME_BRIDGE.Radial_Genesis_Engine.Controller.RGE_Bootstrap import RGERuntime, build_rge
except Exception:  # noqa: BLE001
    RGERuntime = None  # type: ignore[assignment]
    build_rge = None  # type: ignore[assignment]

try:
    from LOGOS_SYSTEM.RUNTIME_BRIDGE.Radial_Genesis_Engine.Core.Task_Triad_Derivation import Constraint, TriadDerivationResult, derive_triad
except Exception:  # noqa: BLE001
    Constraint = None  # type: ignore[assignment]
    TriadDerivationResult = None  # type: ignore[assignment]
    derive_triad = None  # type: ignore[assignment]

try:
    from LOGOS_SYSTEM.RUNTIME_BRIDGE.Radial_Genesis_Engine.Integration.RGE_Nexus_Adapter import RGENexusAdapter
except Exception:  # noqa: BLE001
    RGENexusAdapter = None  # type: ignore[assignment]

__all__ = ["Constraint", "RGENexusAdapter", "RGERuntime", "TriadDerivationResult", "build_rge", "derive_triad"]

# ── Additions from Boundary Repair Pass ──────────────────────────────────────
try:
    from LOGOS_SYSTEM.System_Entry_Point.System_Entry_Point import START_LOGOS, StartupHalt
except Exception:  # noqa: BLE001
    START_LOGOS = None  # type: ignore[assignment]
    StartupHalt = None  # type: ignore[assignment]

