"""
from pathlib import Path

OUTPUT_ROOT = Path("/workspaces/Logos/_Dev_Resources/Reports/Tool_Outputs/Runtime")
OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)


def write_report(name: str, data) -> None:
    path = OUTPUT_ROOT / name
    with open(path, "w", encoding="utf-8") as f:
        import json as _json
        _json.dump(data, f, indent=2)
    print(f"  Report written: {path}")

RUNTIME_TOOL_METADATA
---------------------

tool_name: python_file_list.py
tool_category: Dev_Utilities
tool_subcategory: unspecified

purpose:
Auto-generated placeholder. Tool function description should be updated manually.

authoritative_scope:
LOGOS_SYSTEM

mutation_capability: false
destructive_capability: false
requires_repo_context: true

cli_entrypoint:
python python_file_list.py

output_artifacts:
none

dependencies:
standard_library

safety_classification:
READ_ONLY
"""

# This file is auto-generated by the static AST analysis agent.
# It contains the list of all user Python files to be analyzed.
PYTHON_FILE_LIST = [
    '/workspaces/Logos/LOGOS_SYSTEM/RUNTIME_CORES/RUNTIME_OPPERATIONS_CORE/System_Operations_Protocol/TEST_SUITE/Tests/test_System_Stack_Logos_Agents_I1_Agent_protocol_operations_scp_runtime_work_order.py',
    '/workspaces/Logos/LOGOS_SYSTEM/RUNTIME_CORES/RUNTIME_OPPERATIONS_CORE/System_Operations_Protocol/TEST_SUITE/Tests/test_System_Stack_Logos_Agents_I1_Agent_protocol_operations_scp_tests_run_pipeline_smoke.py',
    '/workspaces/Logos/LOGOS_SYSTEM/RUNTIME_CORES/RUNTIME_OPPERATIONS_CORE/System_Operations_Protocol/TEST_SUITE/Tests/test_System_Stack_Logos_Agents_I1_Agent_protocol_operations_scp_tests_sample_smp.py',
    '/workspaces/Logos/LOGOS_SYSTEM/RUNTIME_CORES/RUNTIME_OPPERATIONS_CORE/System_Operations_Protocol/TEST_SUITE/Tests/test_System_Stack_Logos_Agents_I1_Agent_protocol_operations_scp_transform_iterative_loop.py',
    '/workspaces/Logos/LOGOS_SYSTEM/RUNTIME_CORES/RUNTIME_OPPERATIONS_CORE/System_Operations_Protocol/TEST_SUITE/Tests/test_System_Stack_Logos_Agents_I1_Agent_protocol_operations_scp_transform_transform_registry.py',
    '/workspaces/Logos/LOGOS_SYSTEM/RUNTIME_CORES/RUNTIME_OPPERATIONS_CORE/System_Operations_Protocol/TEST_SUITE/Tests/test_System_Stack_Logos_Agents_I1_Agent_protocol_operations_scp_transform_transform_types.py',
    '/workspaces/Logos/LOGOS_SYSTEM/RUNTIME_CORES/RUNTIME_OPPERATIONS_CORE/System_Operations_Protocol/TEST_SUITE/Tests/test_System_Stack_Logos_Agents_I2_Agent__core_3OT_mediator.py',
    '/workspaces/Logos/LOGOS_SYSTEM/RUNTIME_CORES/RUNTIME_OPPERATIONS_CORE/System_Operations_Protocol/TEST_SUITE/Tests/test_System_Stack_Logos_Agents_I2_Agent__core_bridge_principle_operator.py',
    '/workspaces/Logos/LOGOS_SYSTEM/RUNTIME_CORES/RUNTIME_OPPERATIONS_CORE/System_Operations_Protocol/TEST_SUITE/Tests/test_System_Stack_Logos_Agents_I2_Agent__core_omniproperty_integration.py',
    '/workspaces/Logos/LOGOS_SYSTEM/RUNTIME_CORES/RUNTIME_OPPERATIONS_CORE/System_Operations_Protocol/TEST_SUITE/Tests/test_System_Stack_Logos_Agents_I2_Agent_config_constants.py',
    # ... (truncated for brevity, will include all paths from the list)
]
