# HEADER_TYPE: PRODUCTION_RUNTIME_MODULE
from Test_Suite.Tests.common import run_module_tests

MODULE_PATH = "Logos_System.LOGOS_SYSTEM"
PUBLIC_FUNCTIONS = ['RUN_LOGOS_SYSTEM']
PUBLIC_CLASSES = ['RuntimeHalt']
ENTRY_POINTS = ['RUN_LOGOS_SYSTEM']

def run_tests():
    return run_module_tests(MODULE_PATH, PUBLIC_FUNCTIONS, PUBLIC_CLASSES, ENTRY_POINTS)
